# 异常捕获

- try
  - 执行代码,其中可能有异常.一旦返现异常,则立即到catch执行.否则不会执行catch里面的内容
- catch
  - 除非try里面执行代码发生了异常,否则这里的代码不会执行
- on
  - 当你需要制定异常类型的时候用on
- finally
  - 不管什么情况都会执行,包括try catch 里面用了return
  - 可以理解为只要执行了try或者catch就一定会执行

```dart
void main(){
    // 用法一
      try{
        int result = 12 ~/ 0;
        print("reslt is $result");
      }on IntegerDivisionByZeroException{
        print("Cannot divide by Zero");
      }
    // 用法二
      try{
        int result = 12 ~/ 0;
        print("reslt is $result");
      } catch(e){
        print("error $e");
      }
    // 用法三
      try{
        int result = 12 ~/ 2;
        print("reslt is $result");
      } catch(e,s){
        print("error $e");
        print("详情 $s");
      } finally{
        print("不管有没有异常都会执行");
      }
}
```

---

## 实现自己的异常方法

```dart
void main(){
    try{
        depositMoney(100);
    }catch(e){
        print(e.errorMessage())
    }
}
class XXX implements Exception{
    String errorMessage(){
        return "这是一个自定义的错误";
    }
}
void depositMoney(int amount){
    if(amount < 200){
        throw new XXX();
    }
}
```

